### ISSUE TITLE
Tiebreak

### ISSUE THREAD

**Issue by AustinConlon** [Functional-Organization/Deuce-Android#1]
Something I forgot to mention is that when the set is tied 6 games to 6, a tiebreak game begins. This special game is first to 7 points with a margin of 2 points, and the winner of this game wins the set.

In a tiebreak, the score is presented in the UI and verbally stated by the chair umpire as 0, 1, 2, etc, rather than Love, 15, 30, etc.

**Comment by AustinConlon** [comment]
There is also an "Advantage set" variant where you just play the set until someone is first to 6 games and wins by a margin of 2 games, but I believe tiebreaks are far more common and so would make for a good default.

**Comment by MQDuck** [comment]
Implemented.
