### ISSUE TITLE
Service state

### ISSUE THREAD

**Issue by AustinConlon** [Functional-Organization/Deuce-Android#3]
Service state is displayed with a tennis ball emoji 🎾.

![52176728-95d10c00-276b-11e9-9f47-2ca000f791da](https://user-images.githubusercontent.com/1305957/52176873-e6496900-276d-11e9-9e3e-6f12ed175162.png)
![52176729-95d10c00-276b-11e9-9026-2678642af58d](https://user-images.githubusercontent.com/1305957/52176874-e6e1ff80-276d-11e9-9be8-f609748002ae.png)

**Comment by AustinConlon** [comment]
In a standard non-tiebreak game, service always begins on the right side of the court from the perspective of the serving player (the "deuce side"). If it's the opponent serving in the top half of the interface, the deuce side is on the left in the UI even though from their perspective it's still their right deuce side, since standpoint of the watch wearer the orientation is fixed.

Service alternates horizontally between both sides of the same court half throughout the game. When the game concludes, service changes vertically to the other player in the other court, starting at the deuce side again.

These rules are different for a tiebreak game, as mentioned in the comment below.

![simulator screen shot - apple watch series 4 - 44mm - 2019-02-04 at 22 56 44](https://user-images.githubusercontent.com/1305957/52264389-5844be00-28e6-11e9-8534-5efe4240ed0f.png)

![simulator screen shot - apple watch series 4 - 44mm - 2019-02-04 at 22 56 49](https://user-images.githubusercontent.com/1305957/52264395-5d097200-28e6-11e9-87ee-2696f490416d.png)

![simulator screen shot - apple watch series 4 - 44mm - 2019-02-04 at 22 56 53](https://user-images.githubusercontent.com/1305957/52264405-6266bc80-28e6-11e9-977b-c046b0d77900.png)

![simulator screen shot - apple watch series 4 - 44mm - 2019-02-04 at 22 57 08](https://user-images.githubusercontent.com/1305957/52264407-65fa4380-28e6-11e9-8e20-9e4ffc40d249.png)

**Comment by AustinConlon** [comment]
In a tiebreak, service always begins from the "ad side", the opposite of the deuce side. The service player changes after every total odd point is played - after point 1, point 3, etc. After point 1, service always begins on the deuce side and this pattern continues, only at the start of the tiebreak is service on the ad side.

![simulator screen shot - apple watch series 4 - 44mm - 2019-02-04 at 22 58 05](https://user-images.githubusercontent.com/1305957/52264794-4f082100-28e7-11e9-98f4-60dc57935803.png)

![simulator screen shot - apple watch series 4 - 44mm - 2019-02-04 at 22 58 07](https://user-images.githubusercontent.com/1305957/52264799-53343e80-28e7-11e9-9fa0-bf43b3571f88.png)


![simulator screen shot - apple watch series 4 - 44mm - 2019-02-04 at 22 58 09](https://user-images.githubusercontent.com/1305957/52264807-5af3e300-28e7-11e9-87eb-4daad763e112.png)

![simulator screen shot - apple watch series 4 - 44mm - 2019-02-04 at 22 58 11](https://user-images.githubusercontent.com/1305957/52264817-5f200080-28e7-11e9-8d65-d0493f1ca602.png)

![simulator screen shot - apple watch series 4 - 44mm - 2019-02-04 at 22 58 17](https://user-images.githubusercontent.com/1305957/52264827-647d4b00-28e7-11e9-9c8f-0b3910efb553.png)

![simulator screen shot - apple watch series 4 - 44mm - 2019-02-04 at 22 58 21](https://user-images.githubusercontent.com/1305957/52264834-68a96880-28e7-11e9-9896-2e8dd37966eb.png)

**Comment by AustinConlon** [comment]
After a tiebreak, service changes to the player that didn't begin serving at the start of the tiebreak.

**Comment by MQDuck** [comment]
Done, although I'm not 100% sure that service switching in a doubles tiebreak game is correct.
