### ISSUE TITLE
Training match

### ISSUE THREAD

**Issue by AustinConlon** [Functional-Organization/Deuce-Android#7]
A feature requested is the ability to jump into a training mode without specifying rules at the start. I had some seed of this idea when I'd play with Jon and we weren't sure if we were going to play best-of 3 sets or extend it to best-of 5 sets. This would be especially useful for people who pay for a fixed amount of court time by the hour, which I think is most people.

I'm not sure how exactly rules would be progressively specified as the match goes on, maybe after a set it shows a modal or interactive notification where the user selects there?

**Comment by MQDuck** [comment]
Added "infinite sets" option for open-ended play
